# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.slough.ca
title: The Slough of Despond 
email: salut@slough.ca
author: Slough 
description: > # "Write an awesome description for your new site here. 
  Hamilton based arts, music, and community venue
  copyright: 'Copyright &copy; 2020 The Slough of Despond. All Rights Reserved.'
credits: 

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook 
    url: https://facebook.com/sloughofdespond
  - title: email
    url: mailto:salut@slough.ca
  - title: twitch
    url: https://twitch.tv/theslough
  
