# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://127.0.0.1:4000
title: The Slough of Despond 
email: thesloughofdespond235@gmail.com
author: Slough 
description: > # "Write an awesome description for your new site here. 
  Hamilton based arts, music, and community venue
  copyright: 'Copyright &copy; 2019 Daphne Reed. All Rights Reserved.'
credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: facebook 
    url: https://facebook.com/sloughofdespond
